@extends('web.layout.app')
@section('content')
@include('web.partials.about')
<x-card uri="https://itavolidelvagabondo.ch/" website="itavolidelvagabondo.ch" description="Webseite für Simon Schneeberger a.k.a. I tavoli del vagabondo. Buon appetito." image="itavolidelvagabondo.ch" client="Associazione I tavoli del Vagabondo, Winterthur" design="Pool Practice, Berlin" year="2022" />
<x-card uri="https://20years.quality1.ch/" website="20years.quality1.ch" description="Landingpage für das 20 Jahre Jubiläum der Quality1 AG." image="20years.quality1.ch" client="Quality1 AG, Bubikon" design="Stefanie Wolf" year="2022" />
<x-card uri="https://herkulesdesign.com/" website="herkulesdesign.com" description="Portfolio für die Winterthurer Grafikerin Alexandra Noth." image="herkulesdesign.com" client="Herkules Design GmbH, Winterthur" design="Herkules Design GmbH, Winterthur" year="2021" />
<x-card uri="https://danielh.ch" website="danielh.ch" description="Der Klassiker vom Chreis Cheib. Das Lokal lädt alle ein, die den Mix aus Feinschmecker- und Szenenkultur lieben, die gerne parlieren, dinieren und sich amüsieren." image="danielh.ch" client="Daniel H., Zürich" design="Jam'on digital" year="2021" />
<x-card uri="https://gutebauten.stadt-zuerich.ch/" website="gutebauten.stadt-zuerich.ch" description="Publikums-Votingseite zur Auszeichnung für gute Bauten der Stadt Zürich 2021." image="gute-bauten-stadt-zuerich" client="Stadt Zürich Hochbaudepartement" design="Bivgrafik GmbH, Zürich" year="2021" />
<x-card uri="https://mobilecharge.ch/" website="mobilecharge.ch" description="Landingpage für mobilecharge.ch" image="mobilecharge.ch" client="Ferratec AG, Rudolfstetten" design="Vadim Zvyagintsev " year="2021" />
<x-card uri="https://www.lifework.ch/" website="lifework.ch" description="Corporate Webseite für lifework tk ag in Winterthur" image="lifework.ch" client="lifework tk ag<br>Winterthur" design="Alexandra Noth, Winterthur" year="2021" />
<x-card uri="https://www.riccardacavelti.ch/" website="riccardacavelti.ch" description="Corporate Webseite für die Immobilienexpertin Riccarda Cavelti." image="riccardacavelti" client="Riccarda Cavelti GmbH,<br>Zürich" design="WBG AG – Visuelle Kommunikation, Zürich" year="2021" />
<x-card uri="https://hausermeier.ch" website="hausermeier.ch" description="Portfolio Webseite für das Architektinnen-Duo Martina Hauser und Sabine Meier." image="hausermeier" client="Hauser Meier Architektinnen, Zürich" design="Bivgrafik GmbH, Zürich" year="2020" />
<x-card uri="https://day.ch" website="day.ch" description="Corporate website for the shoe manufacturer Day in Zurich. Online store is coming soon." image="day" client="Day AG, Zürich" design="WBG AG – Visuelle Kommunikation, Zürich" year="2020" />
<x-card uri="https://sipt.ch" website="sipt.ch" description="Webseite und Kursverwaltung für Studenten und Dozenten im Auftrag des Schweizer Instituts für Psychotraumatologie in Winterthur." image="sipt" client="Schweizer Institut für Psychotraumatologie, Winterthur" design="Alexandra Noth, Winterthur" year="2020" />
<x-card uri="https://aas.aero" website="aas.aero" description="Landingpage für Airline Assistance Switzerland." image="aas-aero" client="AAS, Switzerland" design="WBG AG – Visuelle Kommunikation, Zürich" year="2020" />
<x-card uri="https://sajo.ch" website="sajo.ch" description="Online-Shop und Portfolio des Illustrators und Künstlers Samuel Jordi." image="sajo" client="Samuel Jordi, Winterthur" design="Samuel Jordi, Winterthur" year="2020" />
<x-card uri="https://oxid-architektur.ch" website="oxid-architektur.ch" description="Portfolio Webseite für das Zürcher Architekturbüro Oxid." image="oxid-architektur" client="Oxid Architektur GmbH, Zürich" design="Bivgrafik GmbH, Zürich" year="2020" />
<x-card uri="https://mobilecharge.ch" website="mobilecharge.ch" description="Konfigurator für eMobility Ladestationen." image="mobilecharge" client="Ferratec AG, Rudolfstetten" design="Jam'on digital AG, Zürich" year="2020" />
<x-card uri="https://intercable-schweiz.ch" website="intercable-schweiz.ch" description="How to correctly use tools from Intercable." image="intercable-schweiz" client="Ferratec AG, Rudolfstetten" design="marceli.to, Winterthur" year="2020" />
<x-card uri="https://nightnurse.ch" website="nightnurse.ch" description="Visualisierungen. 3D-Animationen. VR-Erlebnisse. Und vieles mehr.. Nightnurse Images AG, Zürich" image="nightnurse" client="Nightnurse Images AG, Zürich" design="WBG AG – Visuelle Kommunikation, Zürich" year="2016 &ndash; 2020" />
<x-card uri="https://rebwein.ch" website="rebwein.ch" description="Webseite und Shop für REB Wein AG, Zürich." image="rebwein" client="Rebwein AG, Zürich" design="Jam'on digital AG, Zürich" year="2019" />
<x-card uri="https://wbg.ch" website="wbg.ch" description="Portfolio Webseite für WBG, Zürich." image="wbg" client="WBG AG – Visuelle Kommunikation, Zürich" design="WBG AG – Visuelle Kommunikation, Zürich" year="2019" />
<x-card uri="https://strut.ch" website="strut.ch" description="Portfolio Webseite für das Winterthurer Architekturbüro Strut Architekten." image="strut" client="Strut Architekten AG, Winterthur" design="Bivgrafik GmbH, Zürich" year="2019" />
<x-card uri="https://studioammeer.ch" website="studioammeer.ch" description="Gesamtauftritte. Gedrucktes. Digitales. Studio am Meer, Winterthur" image="studio-am-meer" client="Studio am Meer, Winterthur" design="Studio am Meer, Winterthur" year="2018" />
@endsection