@extends('web.layout.app')
@section('content')
@include('web.partials.about')
<x-card uri="https://hausermeier.ch" website="hausermeier.ch" description="Portfolio Webseite für das Architektinnen-Duo Martina Hauser und Sabine Meier." image="hausermeier" client="Hauser Meier Architektinnen, Zürich" design="Bivgrafik GmbH, Zürich" year="2020" />
<x-card uri="https://day.ch" website="day.ch" description="Corporate website for the shoe manufacturer Day in Zurich. Online store is coming soon." image="day" client="Day AG, Zürich" design="WBG AG – Visuelle Kommunikation, Zürich" year="2020" />
<x-card uri="https://sipt.ch" website="sipt.ch" description="Webseite und Kursverwaltung für Studenten und Dozenten im Auftrag des Schweizer Instituts für Psychotraumatologie in Winterthur." image="sipt" client="Schweizer Institut für Psychotraumatologie, Winterthur" design="Alexandra Noth, Winterthur" year="2020" />
<x-card uri="https://aas.aero" website="aas.aero" description="Landingpage für Airline Assistance Switzerland." image="aas-aero" client="AAS, Switzerland" design="WBG AG – Visuelle Kommunikation, Zürich" year="2020" />
<x-card uri="https://sajo.ch" website="sajo.ch" description="Online-Shop und Portfolio des Illustrators und Künstlers Samuel Jordi." image="sajo" client="Samuel Jordi, Winterthur" design="Samuel Jordi, Winterthur" year="2020" />
<x-card uri="https://oxid-architektur.ch" website="oxid-architektur.ch" description="Portfolio Webseite für das Zürcher Architekturbüro Oxid." image="oxid-architektur" client="Oxid Architektur GmbH, Zürich" design="Bivgrafik GmbH, Zürich" year="2020" />
<x-card uri="https://mobilecharge.ch" website="mobilecharge.ch" description="Konfigurator für eMobility Ladestationen." image="mobilecharge" client="Ferratec AG, Rudolfstetten" design="Jam'on digital AG, Zürich" year="2020" />
<x-card uri="https://wbg.ch" website="wbg.ch" description="Portfolio Webseite für WBG, Zürich." image="wbg" client="WBG AG – Visuelle Kommunikation, Zürich" design="WBG AG – Visuelle Kommunikation, Zürich" year="2020" />
<x-card uri="https://intercable-schweiz.ch" website="intercable-schweiz.ch" description="How to correctly use tools from Intercable." image="intercable-schweiz" client="Ferratec AG, Rudolfstetten" design="marceli.to, Winterthur" year="2020" />
<x-card uri="https://rebwein.ch" website="rebwein.ch" description="Webseite und Shop für REB Wein AG, Zürich." image="rebwein" client="Rebwein AG, Zürich" design="Jam'on digital AG, Zürich" year="2019" />
<x-card uri="https://strut.ch" website="strut.ch" description="Portfolio Webseite für das Winterthurer Architekturbüro Strut Architekten." image="strut" client="Strut Architekten AG, Winterthur" design="Bivgrafik GmbH, Zürich" year="2019" />
<x-card uri="https://studioammeer.ch" website="studioammeer.ch" description="Gesamtauftritte. Gedrucktes. Digitales. Studio am Meer, Winterthur" image="studio-am-meer" client="Studio am Meer, Winterthur" design="Studio am Meer, Winterthur" year="2018" />
@endsection